name: CI/CD via Self-Hosted Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: narsi421/juice-shop
  SONAR_PROJECT_KEY: juice-shop
  SONAR_PROJECT_NAME: JuiceShop
  DEFECTDOJO_ENGAGEMENT_ID: 1

jobs:
  juice-shop-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Add SonarScanner to PATH
      run: echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

    - name: SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Download All SonarQube Issues (Paginated)
      run: |
        mkdir -p sonarqube-pages
        PAGE=1
        PAGE_SIZE=100
        while true; do
          echo "Fetching SonarQube issues page $PAGE"
          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "${{ secrets.SONAR_URL }}/api/issues/search?componentKeys=${{ env.SONAR_PROJECT_KEY }}&resolved=false&p=$PAGE&ps=$PAGE_SIZE" \
            -o sonarqube-pages/issues-page-${PAGE}.json

          COUNT=$(jq '.issues | length' sonarqube-pages/issues-page-${PAGE}.json)
          if [ "$COUNT" -lt "$PAGE_SIZE" ]; then
            break
          fi
          PAGE=$((PAGE + 1))
        done
        zip -r sonar-issues.zip sonarqube-pages/

    - name: Upload SonarQube Report (ZIP) to DefectDojo
      run: |
        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
          -F "scan_type=SonarQube Scan" \
          -F "engagement=${{ env.DEFECTDOJO_ENGAGEMENT_ID }}" \
          -F "file=@sonar-issues.zip" \
          -F "active=true" \
          -F "verified=true"

    - name: Archive SonarQube Reports
      uses: actions/upload-artifact@v4
      with:
        name: sonarqube-scan-pages
        path: |
          sonar-issues.zip
