name: SonarQube to DefectDojo Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SONAR_PROJECT_KEY: juice-shop
  SONAR_PROJECT_NAME: JuiceShop
  DEFECTDOJO_ENGAGEMENT_ID: 1

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add SonarScanner to PATH
      run: echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

    - name: SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Download SonarQube Report
      run: |
        curl -u ${{ secrets.SONAR_TOKEN }}: \
          "${{ secrets.SONAR_URL }}/api/issues/search?componentKeys=${{ env.SONAR_PROJECT_KEY }}&resolved=false&ps=500" \
          -o sonarqube-report.json
        echo "Report downloaded ($(wc -c < sonarqube-report.json) bytes)"

    - name: Transform Report
      run: |
        # Convert to DefectDojo's expected format
        jq '{
          "issues": .issues
        }' sonarqube-report.json > defectdojo-ready.json

    - name: Upload to DefectDojo (Official Method)
      run: |
        curl -v -X POST \
          "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
          -F "scan_type=SonarQube Scan" \  # Official documented type
          -F "engagement=${{ env.DEFECTDOJO_ENGAGEMENT_ID }}" \
          -F "file=@defectdojo-ready.json" \
          -F "close_old_findings=true" \
          -F "verified=true" \
          -F "active=true" \
          --output response.txt
        
        echo "=== Server Response ==="
        cat response.txt
        grep "HTTP_STATUS" response.txt || echo "No status code received"

    - name: Cleanup
      if: always()
      run: rm -f sonarqube-report.json defectdojo-ready.json response.txt
