name: SonarQube Analysis Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SONAR_PROJECT_KEY: juice-shop
  SONAR_PROJECT_NAME: JuiceShop

jobs:
  sonarqube-analysis:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add SonarScanner to PATH
      run: echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH

    - name: SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Download SonarQube Report
      run: |
        curl -u ${{ secrets.SONAR_TOKEN }}: \
          "${{ secrets.SONAR_URL }}/api/issues/search?componentKeys=${{ env.SONAR_PROJECT_KEY }}&resolved=false" \
          -o sonarqube-report.json

    - name: Archive SonarQube Report
      uses: actions/upload-artifact@v4
      with:
        name: sonarqube-results
        path: sonarqube-report.json
